name: language_learning_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.9.3
  shared_preferences: ^2.2.2
  flutter_tts: ^4.0.2
  provider: ^6.1.5
  http: ^1.2.2
  speech_to_text: ^6.6.2
  permission_handler: ^11.3.1
  camera: ^0.10.6
  google_mlkit_text_recognition: ^0.14.0 # Updated to latest if available
  google_fonts: ^6.1.0
  firebase_auth: ^5.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.68.0
  firebase_core: ^3.6.0
  firebase_database: ^11.3.6
  path_provider: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true